name: Node.js CI

on:
  push:
    branches: [ master, Typescript ]
  pull_request:
    branches: [ master, Typescript ]

jobs:
  # Performs quick checks before the expensive test runs
  quick-test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present
      - name: QuickTest
        run: npm test


  # Runs adapter tests on all supported new node versions and OSes
  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    needs: [quick-test]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Local Tests
        run: npm ci
      - run: npm run build --if-present
      - run: npm run test:integration --if-present
      - run: npm test
